ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: true
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # ===============================
    # WHEEL ODOMETRY
    # ===============================
    odom0: /odom
    odom0_config: [true,  true,  false,
                   false, false, false,
                   true, true, false,
                   false, false, true,
                   false, false, false]
    odom0_differential: false
    odom0_relative: false
    odom0_queue_size: 10
    odom0_pose_rejection_threshold: 5.0
    odom0_twist_rejection_threshold: 1.0

    # ===============================
    # VISUAL ODOMETRY
    # ===============================
    odom1: /vo/odom
    odom1_config: [true,  true,  false,
                   false, false, true,
                   false, false, false,
                   false, false, true,
                   false, false, false]
    odom1_differential: false
    odom1_relative: false
    odom1_queue_size: 10
    odom1_pose_rejection_threshold: 5.0
    odom1_twist_rejection_threshold: 1.0

    # ===============================
    # LIDAR ODOMETRY (SLAM)
    # ===============================
    odom2: /slam_toolbox/odom
    odom2_config: [true,  true,  false,
                   false, false, true,
                   false, false, false,
                   false, false, true,
                   false, false, false]
    odom2_differential: false
    odom2_relative: false
    odom2_queue_size: 10
    odom2_pose_rejection_threshold: 2.0
    odom2_twist_rejection_threshold: 1.0

    # ===============================
    # Process noise covariance
    # ===============================
    process_noise_covariance: [0.05, 0.0,  0.0,   0.0,   0.0,   0.0,
                               0.0,  0.05, 0.0,   0.0,   0.0,   0.0,
                               0.0,  0.0,  1e6,   0.0,   0.0,   0.0,
                               0.0,  0.0,  0.0,   1e3,   0.0,   0.0,
                               0.0,  0.0,  0.0,   0.0,   1e3,   0.0,
                               0.0,  0.0,  0.0,   0.0,   0.0,   0.1]

    # ===============================
    # Initial estimate covariance
    # ===============================
    initial_estimate_covariance: [1e-3, 0.0,   0.0,   0.0,   0.0,   0.0,
                                  0.0,  1e-3,  0.0,   0.0,   0.0,   0.0,
                                  0.0,  0.0,   1e6,   0.0,   0.0,   0.0,
                                  0.0,  0.0,   0.0,   1e3,   0.0,   0.0,
                                  0.0,  0.0,   0.0,   0.0,   1e3,   0.0,
                                  0.0,  0.0,   0.0,   0.0,   0.0,   1e3]

    # ===============================
    # Robustness
    # ===============================
    reset_on_time_jump: true
    print_diagnostics: true
    debug: false

